packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^18.3.1"
  react-dom: "^18.3.1"
  next: "^14.2.18"
  typescript: "^5.7.2"
  "@types/react": "^18.3.12"
  "@types/react-dom": "^18.3.1"
  "@types/node": "^25.0.2"
  eslint: "^9.17.0"
  eslint-config-next: "^14.2.18"
  tailwindcss: "^3.4.17"
  autoprefixer: "^10.4.20"
  postcss: "^8.5.1"
  prettier: "^3.4.2"
  turbo: "^2.3.3"
  "@turbo/gen": "^2.3.3"
  "@changesets/cli": "^2.27.9"