-- Supabase 数据库表创建脚本
-- 在 Supabase Dashboard → SQL Editor 中执行此脚本

-- 创建 docs 表（存储文档）
CREATE TABLE IF NOT EXISTS docs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建 trash 表（回收站）
CREATE TABLE IF NOT EXISTS trash (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  trash_timestamp TEXT NOT NULL UNIQUE
);

-- 创建索引以提升查询性能
CREATE INDEX IF NOT EXISTS idx_docs_slug ON docs(slug);
CREATE INDEX IF NOT EXISTS idx_docs_created_at ON docs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trash_slug_timestamp ON trash(slug, trash_timestamp);
CREATE INDEX IF NOT EXISTS idx_trash_timestamp ON trash(trash_timestamp DESC);

-- 启用行级安全（可选，用于更严格的安全控制）
ALTER TABLE docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE trash ENABLE ROW LEVEL SECURITY;

-- 允许所有操作（简化配置，生产环境应更严格）
CREATE POLICY "Allow all operations on docs" ON docs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on trash" ON trash FOR ALL USING (true) WITH CHECK (true);

-- 创建更新时间戳的触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- 为 docs 表添加触发器
DROP TRIGGER IF EXISTS update_docs_updated_at ON docs;
CREATE TRIGGER update_docs_updated_at
  BEFORE UPDATE ON docs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 验证表创建
SELECT '✅ docs table created successfully' as status;
SELECT '✅ trash table created successfully' as status;
SELECT '✅ Indexes created successfully' as status;
SELECT '✅ Triggers created successfully' as status;
